### ISSUE TITLE
Continuous polling of message queue within milliseconds

### ISSUE THREAD

**Issue by arielfaur** [run-llama/llama_deploy#444]
I'm trying to deploy a workflow locally within a `llama_deploy` container following the documentation. The worflow is successfully deployed but then it enters into a loop of continuous polling to the `http://127.0.0.1:8001/messages/llama_deploy.agentic_workflow` and `http://127.0.0.1:8001/messages/llama_deploy.control_plane`.

Something is wrong but I'm not sure what's causing this polling behavior that goes on infinitely within a 40ms - 60ms interval or so, eventually taking up resources.  Is this expected?

Here's the container log:

```
2025-01-29 21:01:28 🔭 OpenTelemetry Tracing Details 🔭
2025-01-29 21:01:28 |  Phoenix Project: default
2025-01-29 21:01:28 |  Span Processor: SimpleSpanProcessor
2025-01-29 21:01:28 |  Collector Endpoint: http://localhost:6006/v1/traces
2025-01-29 21:01:28 |  Transport: HTTP + protobuf
2025-01-29 21:01:28 |  Transport Headers: {}
2025-01-29 21:01:28 |  
2025-01-29 21:01:28 |  Using a default SpanProcessor. `add_span_processor` will overwrite this default.
2025-01-29 21:01:28 |  
2025-01-29 21:01:28 |  `register` has set this TracerProvider as the global OpenTelemetry default.
2025-01-29 21:01:28 |  To disable this behavior, call `register` with `set_global_tracer_provider=False`.
2025-01-29 21:01:28 
2025-01-29 21:01:28 INFO:     172.17.0.1:55376 - "POST /deployments/create?reload=false HTTP/1.1" 200 OK
2025-01-29 21:01:28 INFO:llama_deploy.message_queues.simple.server - Launching message queue server at http://127.0.0.1:8001/
2025-01-29 21:01:28 2025-01-30 00:01:28,092 - llama_deploy.message_queues.simple.server - INFO - Launching message queue server at http://127.0.0.1:8001/
2025-01-29 21:01:28 INFO:     Started server process [1]
2025-01-29 21:01:28 INFO:     Waiting for application startup.
2025-01-29 21:01:28 INFO:     Application startup complete.
2025-01-29 21:01:28 INFO:     Uvicorn running on http://127.0.0.1:8001 (Press CTRL+C to quit)
2025-01-29 21:01:29 INFO:     127.0.0.1:36730 - "POST /topics/llama_deploy.control_plane HTTP/1.1" 200 OK
2025-01-29 21:01:29 2025-01-30 00:01:29,137 - httpx - INFO - HTTP Request: POST http://127.0.0.1:8001/topics/llama_deploy.control_plane "HTTP/1.1 200 OK"
2025-01-29 21:01:29 INFO:llama_deploy.message_queues.simple.client - Consumer 'ControlPlaneServer-fd625342-ec30-40db-8c5a-8890bdeb81d6' for type 'control_plane' on topic 'llama_deploy.control_plane' has been registered.
2025-01-29 21:01:29 2025-01-30 00:01:29,137 - llama_deploy.message_queues.simple.client - INFO - Consumer 'ControlPlaneServer-fd625342-ec30-40db-8c5a-8890bdeb81d6' for type 'control_plane' on topic 'llama_deploy.control_plane' has been registered.
2025-01-29 21:01:29 INFO:llama_deploy.control_plane.server - Launching control plane server at 127.0.0.1:8000
2025-01-29 21:01:29 2025-01-30 00:01:29,137 - llama_deploy.control_plane.server - INFO - Launching control plane server at 127.0.0.1:8000
2025-01-29 21:01:29 INFO:     Started server process [1]
2025-01-29 21:01:29 INFO:     Waiting for application startup.
2025-01-29 21:01:29 INFO:llama_deploy.services.workflow - Launching agentic_workflow server at 0.0.0.0:8002
2025-01-29 21:01:29 2025-01-30 00:01:29,176 - llama_deploy.services.workflow - INFO - Launching agentic_workflow server at 0.0.0.0:8002
2025-01-29 21:01:29 INFO:     Started server process [1]
2025-01-29 21:01:29 INFO:     Waiting for application startup.
2025-01-29 21:01:29 INFO:     Application startup complete.
2025-01-29 21:01:29 INFO:llama_deploy.services.workflow - Processing initiated.
2025-01-29 21:01:29 2025-01-30 00:01:29,179 - llama_deploy.services.workflow - INFO - Processing initiated.
2025-01-29 21:01:29 INFO:     Application startup complete.
2025-01-29 21:01:29 INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
2025-01-29 21:01:29 INFO:     Uvicorn running on http://0.0.0.0:8002 (Press CTRL+C to quit)
2025-01-29 21:01:29 INFO:     127.0.0.1:36750 - "POST /topics/llama_deploy.agentic_workflow HTTP/1.1" 200 OK
2025-01-29 21:01:29 2025-01-30 00:01:29,181 - httpx - INFO - HTTP Request: GET http://127.0.0.1:8001/messages/llama_deploy.control_plane "HTTP/1.1 200 OK"
2025-01-29 21:01:29 2025-01-30 00:01:29,181 - httpx - INFO - HTTP Request: POST http://127.0.0.1:8001/topics/llama_deploy.agentic_workflow "HTTP/1.1 200 OK"
2025-01-29 21:01:29 INFO:llama_deploy.message_queues.simple.client - Consumer 'WorkflowService-5bb21d3c-c58b-4758-8638-086b98b4eba4' for type 'agentic_workflow' on topic 'llama_deploy.agentic_workflow' has been registered.
2025-01-29 21:01:29 2025-01-30 00:01:29,182 - llama_deploy.message_queues.simple.client - INFO - Consumer 'WorkflowService-5bb21d3c-c58b-4758-8638-086b98b4eba4' for type 'agentic_workflow' on topic 'llama_deploy.agentic_workflow' has been registered.
2025-01-29 21:01:29 INFO:     127.0.0.1:36984 - "POST /services/register HTTP/1.1" 200 OK
2025-01-29 21:01:29 2025-01-30 00:01:29,200 - httpx - INFO - HTTP Request: POST http://127.0.0.1:8000/services/register "HTTP/1.1 200 OK"
2025-01-29 21:01:29 2025-01-30 00:01:29,219 - httpx - INFO - HTTP Request: GET http://127.0.0.1:8001/messages/llama_deploy.agentic_workflow "HTTP/1.1 200 OK"
2025-01-29 21:01:29 2025-01-30 00:01:29,285 - httpx - INFO - HTTP Request: GET http://127.0.0.1:8001/messages/llama_deploy.control_plane "HTTP/1.1 200 OK"
2025-01-29 21:01:29 2025-01-30 00:01:29,322 - httpx - INFO - HTTP Request: GET http://127.0.0.1:8001/messages/llama_deploy.agentic_workflow "HTTP/1.1 200 OK"
2025-01-29 21:01:29 2025-01-30 00:01:29,392 - httpx - INFO - HTTP Request: GET http://127.0.0.1:8001/messages/llama_deploy.control_plane "HTTP/1.1 200 OK"
2025-01-29 21:01:29 2025-01-30 00:01:29,428 - httpx - INFO - HTTP Request: GET http://127.0.0.1:8001/messages/llama_deploy.agentic_workflow "HTTP/1.1 200 OK"
2025-01-29 21:01:29 2025-01-30 00:01:29,500 - httpx - INFO - HTTP Request: GET http://127.0.0.1:8001/messages/llama_deploy.control_plane "HTTP/1.1 200 OK"
2025-01-29 21:01:29 2025-01-30 00:01:29,538 - httpx - INFO - HTTP Request: GET http://127.0.0.1:8001/messages/llama_deploy.agentic_workflow "HTTP/1.1 200 OK"
2025-01-29 21:01:29 2025-01-30 00:01:29,606 - httpx - INFO - HTTP Request: GET http://127.0.0.1:8001/messages/llama_deploy.control_plane "HTTP/1.1 200 OK"
2025-01-29 21:01:29 2025-01-30 00:01:29,645 - httpx - INFO - HTTP Request: GET http://127.0.0.1:8001/messages/llama_deploy.agentic_workflow "HTTP/1.1 200 OK"
2025-01-29 21:01:29 2025-01-30 00:01:29,711 - httpx - INFO - HTTP Request: GET http://127.0.0.1:8001/messages/llama_deploy.control_plane "HTTP/1.1 200 OK"
2025-01-29 21:01:29 2025-01-30 00:01:29,752 - httpx - INFO - HTTP Request: GET http://127.0.0.1:8001/messages/llama_deploy.agentic_workflow "HTTP/1.1 200 OK"
2025-01-29 21:01:29 2025-01-30 00:01:29,815 - httpx - INFO - HTTP Request: GET http://127.0.0.1:8001/messages/llama_deploy.control_plane "HTTP/1.1 200 OK"
2025-01-29 21:01:29 2025-01-30 00:01:29,858 - httpx - INFO - HTTP Request: GET http://127.0.0.1:8001/messages/llama_deploy.agentic_workflow "HTTP/1.1 200 OK"
2025-01-29 21:01:29 2025-01-30 00:01:29,924 - httpx - INFO - HTTP Request: GET http://127.0.0.1:8001/messages/llama_deploy.control_plane "HTTP/1.1 200 OK"
025-01-29 21:01:29 2025-01-30 00:01:29,963 - httpx - INFO - HTTP Request: GET http://127.0.0.1:8001/messages/llama_deploy.agentic_workflow "HTTP/1.1 200 OK"
2025-01-29 21:01:30 2025-01-30 00:01:30,033 - httpx - INFO - HTTP Request: GET http://127.0.0.1:8001/messages/llama_deploy.control_plane "HTTP/1.1 200 OK"
2025-01-29 21:01:30 2025-01-30 00:01:30,073 - httpx - INFO - HTTP Request: GET http://127.0.0.1:8001/messages/llama_deploy.agentic_workflow "HTTP/1.1 200 OK"
2025-01-29 21:01:30 2025-01-30 00:01:30,137 - httpx - INFO - HTTP Request: GET http://127.0.0.1:8001/messages/llama_deploy.control_plane "HTTP/1.1 200 OK"
2025-01-29 21:01:30 2025-01-30 00:01:30,178 - httpx - INFO - HTTP Request: GET http://127.0.0.1:8001/messages/llama_deploy.agentic_workflow "HTTP/1.1 200 OK"
2025-01-29 21:01:30 2025-01-30 00:01:30,243 - httpx - INFO - HTTP Request: GET http://127.0.0.1:8001/messages/llama_deploy.control_plane "HTTP/1.1 200 OK"
2025-01-29 21:01:30 2025-01-30 00:01:30,286 - httpx - INFO - HTTP Request: GET http://127.0.0.1:8001/messages/llama_deploy.agentic_workflow "HTTP/1.1 200 OK"
2025-01-29 21:01:30 2025-01-30 00:01:30,347 - httpx - INFO - HTTP Request: GET http://127.0.0.1:8001/messages/llama_deploy.control_plane "HTTP/1.1 200 OK"
2025-01-29 21:01:30 2025-01-30 00:01:30,394 - httpx - INFO - HTTP Request: GET http://127.0.0.1:8001/messages/llama_deploy.agentic_workflow "HTTP/1.1 200 OK"
2025-01-29 21:01:30 2025-01-30 00:01:30,451 - httpx - INFO - HTTP Request: GET http://127.0.0.1:8001/messages/llama_deploy.control_plane "HTTP/1.1 200 OK"
2025-01-29 21:01:30 2025-01-30 00:01:30,503 - httpx - INFO - HTTP Request: GET http://127.0.0.1:8001/messages/llama_deploy.agentic_workflow "HTTP/1.1 200 OK"
2025-01-29 21:01:30 2025-01-30 00:01:30,558 - httpx - INFO - HTTP Request: GET http://127.0.0.1:8001/messages/llama_deploy.control_plane "HTTP/1.1 200 OK"
2025-01-29 21:01:30 2025-01-30 00:01:30,611 - httpx - INFO - HTTP Request: GET http://127.0.0.1:8001/messages/llama_deploy.agentic_workflow "HTTP/1.1 200 OK"
2025-01-29 21:01:30 2025-01-30 00:01:30,663 - httpx - INFO - HTTP Request: GET http://127.0.0.1:8001/messages/llama_deploy.control_plane "HTTP/1.1 200 OK"
2025-01-29 21:01:30 2025-01-30 00:01:30,718 - httpx - INFO - HTTP Request: GET http://127.0.0.1:8001/messages/llama_deploy.agentic_workflow "HTTP/1.1 200 OK"
2025-01-29 21:01:30 2025-01-30 00:01:30,766 - httpx - INFO - HTTP Request: GET http://127.0.0.1:8001/messages/llama_deploy.control_plane "HTTP/1.1 200 OK"
2025-01-29 21:01:30 2025-01-30 00:01:30,829 - httpx - INFO - HTTP Request: GET http://127.0.0.1:8001/messages/llama_deploy.agentic_workflow "HTTP/1.1 200 OK"
2025-01-29 21:01:30 2025-01-30 00:01:30,871 - httpx - INFO - HTTP Request: GET http://127.0.0.1:8001/messages/llama_deploy.control_plane "HTTP/1.1 200 OK"
2025-01-29 21:01:30 2025-01-30 00:01:30,940 - httpx - INFO - HTTP Request: GET http://127.0.0.1:8001/messages/llama_deploy.agentic_workflow "HTTP/1.1 200 OK"
2025-01-29 21:01:30 2025-01-30 00:01:30,978 - httpx - INFO - HTTP Request: GET http://127.0.0.1:8001/messages/llama_deploy.control_plane "HTTP/1.1 200 OK"
2025-01-29 21:01:31 2025-01-30 00:01:31,052 - httpx - INFO - HTTP Request: GET http://127.0.0.1:8001/messages/llama_deploy.agentic_workflow "HTTP/1.1 200 OK"
2025-01-29 21:01:31 2025-01-30 00:01:31,087 - httpx - INFO - HTTP Request: GET http://127.0.0.1:8001/messages/llama_deploy.control_plane "HTTP/1.1 200 OK"
2025-01-29 21:01:31 2025-01-30 00:01:31,161 - httpx - INFO - HTTP Request: GET http://127.0.0.1:8001/messages/llama_deploy.agentic_workflow "HTTP/1.1 200 OK"
2025-01-29 21:01:31 2025-01-30 00:01:31,192 - httpx - INFO - HTTP Request: GET http://127.0.0.1:8001/messages/llama_deploy.control_plane "HTTP/1.1 200 OK"
...
```

**Comment by logan-markewich** [comment]
@arielfaur this is fixed. You'll need to update your package version (its actually expected when using the SimpleMessageQueue, but we just hide those logs now)

**Comment by logan-markewich** [comment]
PR that fixed this (released in v0.4.2 or newer)
https://github.com/run-llama/llama_deploy/pull/429

**Comment by arielfaur** [comment]
It still happens on v0.5.1.  Whenever I try to run the workflow using the CLI :

`llamactl run --deployment enercruit_agents --arg resume "Hello, I'm Ariel" `

I get this error in the console:
`Error in step 'init_run': 'NoneType' object has no attribute 'content'`

And immediately start to see this polling behavior in the container logs.

Since I've defined an `AgentWorkflow` with multiple agents and tools, I assume this error means that there's no `content` attribute in the initial message?

Here's my workflow definition:
```
async def analize_candidate_resume(ctx: Context, resume: str) -> str:
    """Useful for analyzing and extracting information from a candidate resume. Your input should be a parsed candidate resume in text format."""
    current_state = await ctx.get("state")
    current_state["resume"] = resume
    await ctx.set("state", current_state)
    return "Candidate resume analyzed."

research_agent = ReActAgent(
    name="ResearchAgent",
    description="Useful for getting information about the candidate from their resume and generating a question.",
    system_prompt=(
        "You are the ResearchAgent that can find relevant candidate information and formulate a question that is useful to learn more about their profile."
    ),
    tools=[analize_candidate_resume],
    can_handoff_to=["AskAgent"]
)

...

agent_workflow = AgentWorkflow(
    agents=[research_agent, ask_agent, summary_agent],
    root_agent=research_agent.name,
    initial_state={
        "question": {},
        "candidate_profile": "Not written yet.",
    },
)

def get_workflow():
    return agent_workflow
```

Any idea what could be missing? 
Thanks!

**Comment by logan-markewich** [comment]
You are invoking the workflow wrong, it should be

```
llamactl run --deployment enercruit_agents --arg user_msg "Hello, I'm Ariel" 
```

Need to use the correct kwarg

**Comment by logan-markewich** [comment]
I also don't get the repeating logs

**Comment by masci** [comment]
Closing, feel free to reopen if the problem persists.
